### ISSUE TITLE
Error in control

### ISSUE THREAD

**Issue by VortiK** [Syt-ha/factorio-mod-quick-wagon-filter#1]
Hello, nice mod thanks !

I tested quickly in an ongoing game and got a control script error when filtering a train that was in mouvement : 

![image](https://github.com/Syt-ha/factorio-mod-quick-wagon-filter/assets/23299769/1b53bdfa-94ab-4a98-92db-c853b2ea37fb)

**Comment by Syt-ha** [comment]
Hello @VortiK , thank you for the bug report! 👍 

I was able to recreate the issue and just pushed a fix.

It's live now 🙌 

If you encounter any more hiccups or have suggestions, feel free to let me know.
